### PR TITLE
Fixed an issue where simultaneous failed requests caused multiple redirects

### LINKED ISSUE #903: NavigationDuplicated errors to login and error page
**Describe the bug**
Vue throws a `NavigationDuplicated` error when some redirects to the error and login page occur.

### PR DESCRIPTION
**Pull request by engelhamer**
## Description
In many occasions multiple async requests are fired upon loading a page. If for some reason multiple of these would fail, we would re-route to the error page multiple times as well. This caused `NavigationDuplicated` errors.

An example of when this happened was when a user navigates to the course page of a non existing course. Load attempts were made for both the upcoming deadlines section for that course, the course data itself and the assignments for the course, all of which failed and pushed a 404 paged rapidly after another. The same holds when a user was not logged in.

In general, it would be nice to have these errors more fine-grained (see #904).

## Summary of changes
- Fixes #903

### CODE REVIEW

File: src/vue/src/api/auth.js [hunk 1]
```diff
@@ -104,7 +104,7 @@ function handleError (error, connArgs) {
                 description: response.data.description,
             },
         })
-    } else {
+    } else if (!connArgs.redirect) {
```
Comment (engelhamer) [inline src/vue/src/api/auth.js]: Prevents a flood of toasts if a re-route to the login or error page has taken place already.
