### PR TITLE
Fixed an issue where course details were uneditedable if a course did not contain an LTI assignment

### LINKED ISSUE #755: Editing course details does not work
**Describe the bug**
Editing course details does not work

**To Reproduce**
1. Go to course editor
2. edit the abbriviation for example
3. save

**Screenshots**
image

### PR DESCRIPTION
**Pull request by engelhamer**
## Description
Fixed an issue where course details were uneditedable if a course did not contain an LTI assignment. The `lti_assignment_id_set` is now read-only in the serializer.

## Summary of changes
- Fixes #755

### CODE REVIEW

**Comment by engelhamer** [comment]
The `MainCard` addition was a missing import on the course page.

File: src/vue/src/views/Course.vue [hunk 1]
```diff
@@ -70,6 +70,7 @@ import contentColumns from '@/components/columns/ContentColumns.vue'
 import breadCrumb from '@/components/assets/BreadCrumb.vue'
 import loadWrapper from '@/components/loading/LoadWrapper.vue'
 import assignmentCard from '@/components/assignment/AssignmentCard.vue'
+import mainCard from '@/components/assets/MainCard.vue'
```
Comment (mjvkeulen) [inline src/vue/src/views/Course.vue]: Huh?
