### PR TITLE
Enhancement/nosniff

### LINKED ISSUE #344: Description of assignment not loading
# Bug report

## Expected Behavior
When going to the AssignmentEdit page, you want to see the description of the assignment.

## Actual Behavior
The description of the assignment is empty, only appears after a reload/move back and forth from 2 nodes.

## Steps to Reproduce the Problem
1. login
2. https://ejourn.al/Home/Course/5/Assignment/5/Format

### PR DESCRIPTION
**Pull request by mjvkeulen**
## Description
Hardened the Nginx settings by the addition of the `X-Content-Type-Options "nosniff"`
Worked through all the TextEditor todos in the process.

## Summary of changes
- TextEditor now supports `v-model`, seems like not loading descriptions are fixed in the process of cleanup...
- TextEditor `minifiedTextArea` property:
image
- As you can see, the text editor now also supports `placeholder` text.
- Fixed compatibility issues with modals
- No more ``tinymce.XX Resource interpreted as Stylesheet but transferred with MIME type text/html: XXX`` warnings
- Skins are actually applied, time for a custom skin at some point as we adopt the code with the PR anyway: http://skin.tinymce.com/
- fixes #344, but this will still require staging testing. No issues detected whilst using low traffic debug functions.

### CODE REVIEW

**Comment by engelhamer** [comment]
Does the `v-model` directive solve #344?

**Comment by engelhamer** [comment]
Also: what's with the whitespace above the placeholder?

**Comment by mjvkeulen** [comment]
> Also: what's with the whitespace above the placeholder?

Thats the default `.mce-edit-area` padding, something which we should make our own at some point. I could not get the selector right, but such changes could be passed to the `content_style` config data of the TextEditor component.

**Comment by engelhamer** [comment]
Nice to see #344 has actually been fixed!

File: src/vue/src/components/template/TemplateEdit.vue [hunk 1]
```diff
@@ -47,9 +47,10 @@
                                 v-if="showEditors"
                                 :id="`rich-text-editor-field-${template.id}-${field.location}`"
                                 :basic="true"
-                                :footer="false"
-                                :givenContent="field.description ? field.description : ''"
-                                @content-update="field.description = $event"
+                                :displayInline="true"
+                                :minifiedTextArea="true"
+                                placeholder="Optional description"
```
Comment (engelhamer) [inline src/vue/src/components/template/TemplateEdit.vue]: The inline display looks a bit funny: there is way more padding at the top than necessary, but less at the sides. Compare:

image

with:

image

The location of the placeholder should be the same as regular text.

Also, when you click the texteditor above the placeholder text, a cursor appears while the placeholder is not removed. The formatting tools also do not become available then.

Comment (engelhamer) [reply src/vue/src/components/template/TemplateEdit.vue]: Additionally, the placeholder is in regular Roboto whereas the actual description is in Roboto Condensed. I think the texteditor as a whole should use only Roboto, since that will be used when the contents are displayed as well.

File: src/vue/src/components/assets/TextEditor.vue [hunk 2]
```diff
@@ -112,7 +112,8 @@ export default {
                 content_style: `
                     @import url('https://fonts.googleapis.com/css?family=Roboto+Condensed|Roboto:400,700');
                     body {
-                        font-family: "Roboto Condensed";
+                        font-family: 'Roboto Condensed';
```
Comment (engelhamer) [inline src/vue/src/components/assets/TextEditor.vue]: Should add `sans-serif` as a backup.

File: src/vue/src/components/assets/TextEditor.vue [hunk 3]
```diff
@@ -299,6 +301,12 @@ export default {
                 {start: '* ', cmd: 'InsertUnorderedList'},
                 {start: '- ', cmd: 'InsertUnorderedList'}
             ]
+        },
+        /* NOTE: Called from parent. */
+        clearContent () {
+            this.editor.setContent('')
+            this.editor.execCommand('fontName', false, 'roboto condensed', {skip_focus: true})
```
Comment (engelhamer) [inline src/vue/src/components/assets/TextEditor.vue]: Should the font name not be capitalised?
